services:
  - type: web
    name: flask-server-only
    env: python
    buildCommand: |
      cd server
      pip install -r requirements.txt
    startCommand: |
      cd server
      python app.py
    envVars:
      - key: FLASK_ENV
        value: production

